import type { AssetId } from './asset';
import type { CategoryId } from './category';
import type { RecurringRuleId } from './recurring-rule';
import type { WishlistItemId } from './wishlist-item';
import type { CalendarDate, Id, Money, Timestamp } from '../values';

export type TransactionId = Id<'Transaction'>;

export const TRANSACTION_TYPES = ['income', 'expense', 'transfer'] as const;
export type TransactionType = (typeof TRANSACTION_TYPES)[number];

/**
 * How the money moved (e.g. "cash", "card"). The Step 0 spec names this
 * field but does not enumerate values, so it is free text here (non-blank
 * when present).
 */
export type PaymentMethod = string;

interface TransactionBase {
  readonly id: TransactionId;
  /** Always positive. Direction comes from `type`, never from a sign. */
  readonly amount: Money;
  readonly date: CalendarDate;
  readonly description: string;
  readonly createdAt: Timestamp;
  readonly updatedAt: Timestamp;
  /** Set when this Transaction was created by purchasing a WishlistItem. */
  readonly sourceWishlistItemId?: WishlistItemId;
  /** Set when this Transaction was generated by a RecurringRule. */
  readonly recurringRuleId?: RecurringRuleId;
}

export interface IncomeTransaction extends TransactionBase {
  readonly type: 'income';
  readonly assetId: AssetId;
  readonly categoryId: CategoryId;
  readonly paymentMethod: PaymentMethod;
  readonly sourceAssetId?: never;
  readonly destinationAssetId?: never;
}

export interface ExpenseTransaction extends TransactionBase {
  readonly type: 'expense';
  readonly assetId: AssetId;
  readonly categoryId: CategoryId;
  readonly paymentMethod: PaymentMethod;
  readonly sourceAssetId?: never;
  readonly destinationAssetId?: never;
}

/** Moves money between two assets. Has no category and no `assetId`. */
export interface TransferTransaction extends TransactionBase {
  readonly type: 'transfer';
  readonly sourceAssetId: AssetId;
  readonly destinationAssetId: AssetId;
  readonly paymentMethod?: PaymentMethod;
  readonly assetId?: never;
  readonly categoryId?: never;
}

export type Transaction =
  IncomeTransaction | ExpenseTransaction | TransferTransaction;
